# abseil 20230802 now only support MacOS >=10.13, reflect this here
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.13"                # [osx and x86_64]

CONDA_BUILD_SYSROOT:       # [osx and x86]
  - /opt/MacOSX10.13.sdk   # [osx and x86]

c_compiler:  # [win]
  - vs2019   # [win]
cxx_compiler:  # [win]
  - vs2019     # [win]
vc:                          # [win]
  - 16                       # [win]

