libabseil: 20250814.1

c_compiler:                # [win]
  - clang                  # [win]
cxx_compiler:              # [win]
  - clang                  # [win]

c_compiler_version:        # [win]
  - 20                     # [win]
cxx_compiler_version:      # [win]
  - 20                     # [win]