{% set name = "protobuf" %}
{% set version = "3.4.1" %}
{% set sha256 = "8e0236242106e680b4f9f576cc44b8cd711e948b20a9fc07769b0a20ceab9cc4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/google/protobuf/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  #git_url: https://github.com/google/protobuf.git
  #git_tag: v3.4.1

build:
  number: 0
  # protobuf does not support Visual C++ 2008 well due to poor c++11 support
  # For the time being skip VS2008 builds, fix if these are needed
  skip: True  # [win and vc<10]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - libprotobuf {{ version }}
    - six
  run:
    - python
    - six

test:
  commands:
    - protoc --help
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
  imports:
    - google
    - google.protobuf
    - google.protobuf.internal
    - google.protobuf.pyext

about:
  home: https://developers.google.com/protocol-buffers/
  license: New BSD License
  license_family: BSD
  license_file: LICENSE
  summary: Protocol Buffers - Google's data interchange format
  description: |
    Protocol buffers are Google's language-neutral, platform-neutral, extensible
    mechanism for serializing structured data,think XML, but smaller, faster, and simpler.
  doc_url: https://developers.google.com/protocol-buffers/docs/tutorials
  doc_source_url: https://github.com/google/protobuf/blob/master/README.md
