{% set name = "protobuf" %}
{% set version = "3.4.1" %}
{% set sha256 = "8e0236242106e680b4f9f576cc44b8cd711e948b20a9fc07769b0a20ceab9cc4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/google/protobuf/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches: 
      - 3754.patch
        #- 3494.patch
  - url: https://github.com/google/googlemock/archive/release-1.7.0.zip
    fn: googlemock-release-1.7.0.zip
    folder: gmock
  - url: https://github.com/google/googletest/archive/release-1.7.0.zip
    fn: googletest-release-1.7.0.zip
    folder: gmock/gtest

build:
  number: 0
  skip: True  # [win and py27]
  features:
    - vc{{ vc }}   # [win]
  run_exports:
    # breaks backwards compatibility and new SONAME each minor release
    # https://abi-laboratory.pro/tracker/timeline/protobuf/
    - {{ pin_subpackage('protobuf', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf           # [unix]
    - automake           # [unix]
    - libtool            # [unix]
    - pkg-config         # [unix]
    - unzip              # [unix]
    - cmake              # [win]
    - git                # [win]
  host:
    - ordereddict        # [py26]
    - python
    - setuptools
    - six
    - unittest2          # [py26]
    - zlib
  run:
    - ordereddict        # [py26]
    - python
    - setuptools
    - six
    - unittest2          # [py26]
    - zlib

test:
  commands:
    - protoc --help
    - test -f ${PREFIX}/lib/libprotobuf.a                           # [unix]
    - test -f ${PREFIX}/lib/libprotobuf.dylib                       # [osx]
    - test -f ${PREFIX}/lib/libprotobuf.so                          # [linux]
    - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1   # [win]
    - python -c "from google.protobuf.internal import api_implementation; assert api_implementation.Type() == 'cpp'"  # [unix]
    - python -c "from google.protobuf.internal import api_implementation; assert api_implementation.Type() == 'python'"  # [win]
  imports:
    - google
    - google.protobuf
    - google.protobuf.internal
    - google.protobuf.pyext

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: "Protocol Buffers - Google's data interchange format."

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - hajapy
