{% set version = "3.5.2" %}

package:
  name: protobuf
  version: {{ version }}

source:
  url: https://github.com/google/protobuf/archive/v{{ version }}/protobuf-v{{ version }}.tar.gz
  sha256: 4ffd420f39f226e96aebc3554f9c66a912f6cad6261f39f194f16af8a1f6dab2

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib 1.2.11
    - python
    - setuptools
    - libprotobuf {{ version }}
    - six
    - ordereddict                # [py26]
    - unittest2                  # [py26]
  run:
    - zlib 1.2.11
    - python
    - setuptools
    - libprotobuf {{ version }}
    - six
    - ordereddict                # [py26]
    - unittest2                  # [py26]

test:
  commands:
    - python -c "from google.protobuf.internal import api_implementation; assert api_implementation.Type() == 'cpp'"  # [unix]
    - python -c "from google.protobuf.internal import api_implementation; assert api_implementation.Type() == 'python'"  # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
  imports:
    - google
    - google.protobuf
    - google.protobuf.internal
    - google.protobuf.pyext
    - google.protobuf.util
    - google.protobuf.compiler

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Protocol Buffers - Google's data interchange format."
  description: |
    Protocol buffers are Google's language-neutral, platform-neutral, extensible
    mechanism for serializing structured data,think XML, but smaller, faster, and simpler.
  doc_url: https://developers.google.com/protocol-buffers/docs/tutorials
  doc_source_url: https://github.com/google/protobuf/blob/master/README.md

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - hajapy
