{% set version = "3.6.1" %}

package:
  name: protobuf
  version: {{ version }}

source:
  url: https://github.com/google/protobuf/archive/v{{ version }}/protobuf-v{{ version }}.tar.gz
  sha256: 3d4e589d81b2006ca603c1ab712c9715a76227293032d05b26fca603f90b3f5b

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - python
    - setuptools
    - libprotobuf {{ version }}
    - six
    - ordereddict                # [py26]
    - unittest2                  # [py26]
  run:
    - zlib
    - python
    - setuptools
    - libprotobuf {{ version }}
    - six
    - ordereddict                # [py26]
    - unittest2                  # [py26]

test:
  commands:
    - python -c "from google.protobuf.internal import api_implementation; assert api_implementation.Type() == 'cpp'"  # [unix]
    - python -c "from google.protobuf.internal import api_implementation; assert api_implementation.Type() == 'python'"  # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
  imports:
    - google
    - google.protobuf
    - google.protobuf.internal
    - google.protobuf.pyext
    - google.protobuf.util
    - google.protobuf.compiler

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: "Protocol Buffers - Google's data interchange format."

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - hajapy
